LINEAR PREDICTION MODEL TO TRACK CAR PRICE

In [2]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder # for scaling and encoding
from sklearn.model_selection import train_test_split

car_df = pd.read_csv('used_car_price_prediction_1M.csv')
car_df

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
0,Toyota,Camry,2001,19.615852,1396.560379,NaN,Hybrid,Automatic,First,Grey,Chennai,500928,1,1,0,1,4,5,24,3.531896e+05
1,Hyundai,i20,2012,19.478608,1130.771005,137.021719,Petrol,NaN,First,Grey,Mumbai,211510,0,1,0,1,4,5,13,9.596943e+05
2,Mahindra,Bolero,2008,17.469920,1766.466250,142.902961,NaN,Automatic,First,Black,Kolkata,333999,1,0,0,1,5,5,17,2.920229e+05
3,BMW,X1,2015,21.295421,NaN,49.782079,NaN,Manual,First,White,Pune,225930,1,1,3,1,4,5,10,2.949453e+06
4,Honda,Civic,2022,18.326833,1239.334935,121.505993,Diesel,Manual,Second,White,Kolkata,43404,1,0,0,1,5,5,3,6.365208e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004995,Nissan,Magnite,2022,12.256422,1773.657889,117.574596,Petrol,Manual,First,Black,Ahmedabad,68571,1,0,0,1,4,5,3,1.104233e+06
1004996,Honda,Amaze,2005,NaN,1705.773023,99.643689,CNG,Automatic,First,NaN,Pune,311400,1,1,0,1,4,5,20,7.122346e+05
1004997,Skoda,Octavia,2018,21.665335,1447.159515,NaN,Petrol,NaN,First,Brown,Delhi,42140,0,1,0,1,4,4,7,1.304198e+06
1004998,BMW,X3,2010,17.852635,2179.906631,NaN,Petrol,Manual,First,Brown,Mumbai,211980,0,1,0,1,4,7,15,1.866610e+06
1004999,Ford,Endeavour,2010,20.839002,800.000000,11.857082,Petrol,Manual,First,Blue,Kolkata,273045,1,1,0,1,4,7,15,5.000000e+04

In [3]:
car_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1005000 entries, 0 to 1004999
Data columns (total 20 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Brand             1005000 non-null  str
 1   Model             1005000 non-null  str
 2   Year              1005000 non-null  int64
 3   Mileage_kmpl      924610 non-null   float64
 4   Engine_CC         924597 non-null   float64
 5   Horsepower        924597 non-null   float64
 6   Fuel_Type         926267 non-null   str
 7   Transmission      924615 non-null   str
 8   Owner_Type        1005000 non-null  str
 9   Color             924581 non-null   str
 10  City              924570 non-null   str
 11  Kms_Driven        1005000 non-null  int64
 12  Insurance_Valid   1005000 non-null  int64
 13  Service_History   1005000 non-null  int64
 14  Accidents         1005000 non-null  int64
 15  Tax_Paid          1005000 non-null  int64
 16  Number_of_Doors   1005000 non-null  int64
 17  Seats             1005000 non-null  int64
 18  Registration_Age  1005000 non-null  int64
 19  Price             1005000 non-null  float64
dtypes: float64(4), int64(9), str(7)
memory usage: 153.4 MB

In [4]:
car_df.describe()

,Year,Mileage_kmpl,Engine_CC,Horsepower,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
count,1.005000e+06,924610.000000,924597.000000,924597.000000,1.005000e+06,1.005000e+06,1.005000e+06,1.005000e+06,1.005000e+06,1.005000e+06,1.005000e+06,1.005000e+06,1.005000e+06
mean,2.011996e+03,17.996048,1506.627079,120.571877,2.028639e+05,8.494607e-01,7.507602e-01,2.994786e-01,9.002637e-01,4.248505e+00,5.160250e+00,1.300429e+01,1.012897e+06
std,7.211486e+00,3.993600,386.034245,36.775150,1.753705e+05,3.575994e-01,4.325731e-01,5.473250e-01,2.996483e-01,6.988041e-01,9.140884e-01,7.211486e+00,1.141645e+06
min,2.000000e+03,5.000000,800.000000,-18.509982,5.000000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,5.000000e+04
25%,2.006000e+03,15.301694,1230.406732,94.840538,8.455500e+04,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,4.000000e+00,5.000000e+00,7.000000e+00,3.433504e+05
50%,2.012000e+03,17.998362,1500.181272,120.052791,1.663130e+05,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,4.000000e+00,5.000000e+00,1.300000e+01,7.589083e+05
75%,2.018000e+03,20.689159,1769.598840,145.477891,2.863800e+05,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.000000e+00,5.000000e+00,1.900000e+01,1.293475e+06
max,2.024000e+03,36.281737,3362.023486,290.249839,4.368000e+06,1.000000e+00,1.000000e+00,5.000000e+00,1.000000e+00,5.000000e+00,7.000000e+00,2.500000e+01,3.788600e+07

In [5]:
car_df.head(10)

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
0,Toyota,Camry,2001,19.615852,1396.560379,NaN,Hybrid,Automatic,First,Grey,Chennai,500928,1,1,0,1,4,5,24,3.531896e+05
1,Hyundai,i20,2012,19.478608,1130.771005,137.021719,Petrol,NaN,First,Grey,Mumbai,211510,0,1,0,1,4,5,13,9.596943e+05
2,Mahindra,Bolero,2008,17.469920,1766.466250,142.902961,NaN,Automatic,First,Black,Kolkata,333999,1,0,0,1,5,5,17,2.920229e+05
3,BMW,X1,2015,21.295421,NaN,49.782079,NaN,Manual,First,White,Pune,225930,1,1,3,1,4,5,10,2.949453e+06
4,Honda,Civic,2022,18.326833,1239.334935,121.505993,Diesel,Manual,Second,White,Kolkata,43404,1,0,0,1,5,5,3,6.365208e+05
5,Toyota,Camry,2007,NaN,1513.157430,100.927306,Petrol,Automatic,Second,NaN,NaN,321426,0,0,1,1,4,2,18,5.195264e+05
6,Hyundai,i20,2014,16.328654,1398.722600,111.846497,Diesel,Manual,First,NaN,Chennai,200343,1,0,0,1,4,4,11,4.953191e+05
7,Hyundai,Creta,2001,21.895120,800.000000,0.709766,Petrol,Manual,Second,White,Kolkata,228720,1,0,0,1,5,5,24,5.000000e+04
8,Volkswagen,Taigun,2020,17.461847,1397.891768,104.095168,Diesel,Automatic,Fourth+,Black,Hyderabad,122025,1,1,0,1,4,5,5,1.045347e+06
9,Audi,A4,2009,12.062221,1618.723936,86.071024,Petrol,Manual,Second,Blue,Pune,395200,1,1,1,1,5,7,16,2.633309e+05

In [ ]:
car_df.tail(10)

# YOU CAN ALSO USE iloc[] to peak through records at specific locations

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
1004990,Skoda,Slavia,2008,13.935683,1287.775569,114.498130,Petrol,Manual,First,Red,Hyderabad,269892,1,1,0,0,4,7,17,3.963039e+05
1004991,Skoda,Slavia,2003,19.946978,1252.293439,115.394192,CNG,Manual,First,Grey,Bangalore,533082,1,1,0,1,4,2,22,5.000000e+04
1004992,Tata,Nexon,2020,NaN,1670.435775,158.228921,NaN,Manual,First,Blue,NaN,97025,1,1,0,1,2,5,5,7.559451e+05
1004993,Tata,Harrier,2017,23.199875,1563.247126,NaN,Petrol,Manual,First,White,Kolkata,162568,1,0,0,1,5,5,8,9.951965e+05
1004994,Volkswagen,Virtus,2014,NaN,1111.514707,121.577474,Petrol,Manual,Third,Brown,Chennai,194304,1,1,0,0,5,5,11,1.002635e+06
1004995,Nissan,Magnite,2022,12.256422,1773.657889,117.574596,Petrol,Manual,First,Black,Ahmedabad,68571,1,0,0,1,4,5,3,1.104233e+06
1004996,Honda,Amaze,2005,NaN,1705.773023,99.643689,CNG,Automatic,First,NaN,Pune,311400,1,1,0,1,4,5,20,7.122346e+05
1004997,Skoda,Octavia,2018,21.665335,1447.159515,NaN,Petrol,NaN,First,Brown,Delhi,42140,0,1,0,1,4,4,7,1.304198e+06
1004998,BMW,X3,2010,17.852635,2179.906631,NaN,Petrol,Manual,First,Brown,Mumbai,211980,0,1,0,1,4,7,15,1.866610e+06
1004999,Ford,Endeavour,2010,20.839002,800.000000,11.857082,Petrol,Manual,First,Blue,Kolkata,273045,1,1,0,1,4,7,15,5.000000e+04