In [1]:
import pandas as pd
import matplotlib
import matplotlib as plt
import numpy as np
import plotly.express as px 
import seaborn as sns

# %matplotlib inline - to ensure charts created are shown directly and not as pop ups

titanic_df = pd.read_csv('test.csv')
titanic_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [2]:
print(titanic_df.head())
print(titanic_df.info())
print(titanic_df.describe())

   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S
<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB
None

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [3]:
print(titanic_df.isnull().sum(),'\n')         # count missing per column
print(titanic_df.isnull().mean()*100)    # % missing per column

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

PassengerId     0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [4]:
# Drop a column that's mostly missing (deck: 688/891 missing)
titanic_df.drop(columns='Cabin', inplace=True)

# Input a reasonable numeric value to Age and Fare  column (median)
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].median())
titanic_df['Fare'] = titanic_df['Fare'].fillna(titanic_df['Fare'].median())
titanic_df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [5]:
# CHECKING PRESENCE OF ANY DUPLICATES
print(titanic_df.duplicated().sum())

# 3. REMOVING DUPLICATES - since there are no duplicate values
# titanic_df = titanic_df.drop_duplicates()

0

In [6]:
# 4. FIXING DATA TYPES
# Example: converting a date string column (if present)
# df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')

print(titanic_df.dtypes,'\n')
titanic_df['Age'] = titanic_df['Age'].astype('int')
print(titanic_df.dtypes)

PassengerId      int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

PassengerId      int64
Pclass           int64
Name               str
Sex                str
Age              int64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

In [7]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          418 non-null    int64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         418 non-null    float64
 9   Embarked     418 non-null    str
dtypes: float64(1), int64(5), str(4)
memory usage: 32.8 KB

In [8]:
titanic_df.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22,1,1,3101298,12.2875,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14,0,0,7538,9.2250,S
6,898,3,"Connolly, Miss. Kate",female,30,0,0,330972,7.6292,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26,1,1,248738,29.0000,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18,0,0,2657,7.2292,C
9,901,3,"Davies, Mr. John Samuel",male,21,2,0,A/4 48871,24.1500,S

In [10]:
# added settings to improve the styles for our charts

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor'] = '00000000'

In [ ]:
# EXPLORATORY DATA ANALYSIS FOR AGE.
titanic_df.Age.describe()

count    418.000000
mean      29.574163
std       12.721533
min        0.000000
25%       23.000000
50%       27.000000
75%       35.750000
max       76.000000
Name: Age, dtype: float64

In [26]:
fig =px.histogram(
    titanic_df,
    x='Age',
    marginal='box',
    nbins = 50,
    title='DISTRIBUTION OF AGE'
)

fig.update_layout(bargap=0.2)
fig.show()

In [ ]:
# removing the ouliers

Q1 = titanic_df['Age'].quantile(0.25)
Q3 = titanic_df['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Outlier bounds for Age: {lower_bound:.2f} to {upper_bound:.2f}")

# Option A: Remove outliers
# below= titanic_df['Age'] >= lower_bound
# above= titanic_df['Age'] <= upper_bound
# titanic_df_no_outliers = titanic_df[ below & above]

# titanic_df_no_outliers

# Option B: Cap outliers instead of removing (winsorizing)
# titanic_df['Age'] = np.clip(titanic_df['Age'], lower_bound, upper_bound)
# titanic_df

In [27]:
fig =px.histogram(
    titanic_df_no_outliers,
    x='Fare',
    marginal='box',
    nbins = 50,
    title='DISTRIBUTION OF FARE'
)

fig.update_layout(bargap=0.2)
fig.show()

In [28]:
# DEALING WITH THE OUTLIERS

Q1 = titanic_df['Fare'].quantile(0.25)
Q3 = titanic_df['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Outlier bounds for Fare: {lower_bound:.2f} to {upper_bound:.2f}")

# Option A: Remove outliers
# below= titanic_df['Fare'] >= lower_bound
# above= titanic_df['Fare'] <= upper_bound
# titanic_df_no_outliers = titanic_df[ below & above]

# titanic_df_no_outliers

Outlier bounds for Fare: -27.47 to 66.84